# Loads Home Assistant's default integrations.
default_config:

homeassistant:
  packages: !include_dir_named packages
  unit_system: metric

frontend:
  themes: !include_dir_merge_named themes

family_dashboard_guard:

family_camera_streams:

lovelace:
  resource_mode: yaml
  resources:
    - url: /local/community/bubble-card/bubble-card.js?v=3.2.5
      type: module
    - url: /local/community/button-card/button-card.js?v=7.0.1
      type: module
    - url: /local/community/navbar-card/navbar-card.js?v=1.6.1
      type: module
    - url: /local/community/card-mod/card-mod.js?v=4.2.1
      type: module
    - url: /local/community/kiosk-mode/kiosk-mode.js?v=14.0.2
      type: module
    - url: /local/community/auto-entities/auto-entities.js?v=1.16.1
      type: module
    - url: /local/community/todo-swipe-card/todo-swipe-card.js?v=3.6.0
      type: module
  dashboards: !include dashboards/lovelace-dashboards.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
